from pygame.locals import *

# constants
GREEN=(0x14, 0xAE, 0x5C)
RED=(0xF2, 0x48, 0x22)
BACKGROUND=(0x1E, 0x1E, 0x1E)
SKY_BLUE=(0x0D, 0x99, 0xFF)
WHITE_GRAY=(0xE6, 0xE6, 0xE6)
WHITE=(255, 255, 255)
GOLD=(0xFF, 0xE8, 0xA3)
BLACK=(0, 0, 0)
CYAN=(0x33, 0xFF, 0xFF)
GRAY=(0xB3, 0xB3, 0xB3)
DARK_GRAY=(0x75, 0x75, 0x75)
PINK=(0xFF, 0xC7, 0xC2)

MIN_WIDTH=777
MIN_HEIGHT=560
DESIRED_EFFECTS=HWSURFACE|DOUBLEBUF|RESIZABLE
LEFT_TAB=119
IMPORT_TOP=98
SELECT_DEVICE_TOP=274
SELECTED_BUBBLE_TOP=442
BLUE_WIDTH=414
BLUE_HEIGHT=112
BUBBLE_HEIGHT=176
BLUE_RADIUS=6
BUBBLE_RADIUS=70
METRIC_TAB=141
TEMPO_TOP=755
TEMPO_WIDTH=138
TEMPO_HEIGHT=60
REGULAR_FONT_FACTOR=24
LARGE_FONT_FACTOR=40
DEVICE_SELECTED_OFFSET=30
LEFT_TEMPO_BOX=300
TEMPO_BOX_TOP=770
TEMPO_BOX_WIDTH=93
TEMPO_BOX_HEIGHT=70
INCREMENTER_TOP=770
INCREMENTER_LEFT=420
DECREMENTER_BOTTOM=834
AUGMENTER_HEIGHT=30
PLAY_BUTTON_LEFT=1132
PLAY_BUTTON_TOP=960
PLAY_HEIGHT=80
NEXT_MEASURE_OFFSET=160
NEXT_BUTTON_REFACTOR=9
AUDIVERIS_OUTPUT_LOCATION="C:/Users/khand/OneDrive/Documents/GitHub/d7-accompanyBot/Outputs"
MEASURE_SLIDER_X=756
MEASURE_SLIDER_Y=890
MEASURE_SLIDER_WIDTH=686
MEASURE_SLIDER_THICKNESS=5
ORBX=MEASURE_SLIDER_X
ORBY=MEASURE_SLIDER_Y+(MEASURE_SLIDER_THICKNESS//2)
ORB_RADIUS=12
INPUT_BUFFER=100000000
METRICS_HEIGHT_OFFSET=60
METRIC_WIDTH_OFFSET=40
POPPLER_PATH="C:/Users/khand/OneDrive/Documents/GitHub/d7-accompanyBot/poppler-23.01.0/Library/bin"
MIDI_STRING="CachedMusicXML/digital.midi"
MAX_MUSIC_WIDTH=735
MAX_MUSIC_HEIGHT=800
MUSIC_CENTER_X=1110
MUSIC_CENTER_Y=450
ARDUINO_PORT="Arduino MKRZERO"
ARDUINO_PORT_ALT="Arduino Uno"
BAD_PORT="bootloader"
COMM_TIMEOUT=0.2
KILL_TIMER=0.1
RPI_SCP_ADDR="team-d7@172.26.171.141"
RPI_MUSIC_DIR="~/d7-accompanyBot/XMLFiles/"
DEFAULT_BAUD=115200
DISP_TEXT = "Place AccompanyBot at octave "
FIX_FACTOR = 120
CACHE_REQUEST="cacherequest"
EXISTING_FILE="existing"
REPROCESS_FILE="reprocess"
PARTIAL_EXIST_STR=" already exists. Use this file or reprocess sheet music? (Reprocessing could take a while...)"
CURRENT_XML="currentxml"
DELETE_CMD="Remove-Item"
FORCE_FLAG="-Force"
RECURSE_FLAG="-Recurse"


### XML Fixes ###
PART_VOICE="<part-name>Voice</part-name>"
PART_PIANO="<part-name>Piano</part-name>"
INSTRUMENT_VOICE="<instrument-name>Voice Oohs</instrument-name>"
INSTRUMENT_PIANO="<instrument-name>Acoustic Grand Piano</instrument-name>"
MIDI_PROGRAM_VOICE="<midi-program>54</midi-program>"
MIDI_PROGRAM_PIANO="<midi-program>1</midi-program>"

### transmission commands ###
PAUSE_COMMAND="P\n"
PLAY_COMMAND="S\n"
MEASURE_COMMAND="measure"
TEMPO_COMMAND="tempo"
KILL_COMMAND="kill"
COUNT_COMMAND="number"
OCTAVE_COMMAND="octave"
SEND_FILE="file"
LATENCY_TEST="latency"

# display cache message
BLOCK_MESSAGE_X=792
BLOCK_MESSAGE_Y=108
BLOCK_MESSAGE_WIDTH=636
BLOCK_MESSAGE_HEIGHT=317
BLOCK_MESSAGE_COLOR=(0xBB, 0xA0, 0xBD)
BLOCK_RADIUS=5

BLOCK_TEXT_X=888
BLOCK_TEXT_Y=137
BLOCK_TEXT_WIDTH=472
BLOCK_TEXT_HEIGHT=120
CACHE_TEXT_FONT=24
CACHE_TEXT_COLOR=(0x0D, 0x36, 0x86)

GREEN_BUTTON_X=845
GREEN_BUTTON_Y=283
GREEN_BUTTON_WIDTH=223
GREEN_BUTTON_HEIGHT=113
GREEN_BUTTON_COLOR=(0x61, 0xC2, 0x76)

ORANGE_BUTTON_X=1150
ORANGE_BUTTON_Y=283
ORANGE_BUTTON_WIDTH=223
ORANGE_BUTTON_HEIGHT=113
ORANGE_BUTTON_COLOR=(0xD3, 0x82, 0x24)


FIGMA_SCREEN_WIDTH=1626
FIGMA_SCREEN_HEIGHT=1170